import { spawnSync } from "child_process";
import * as fs from "fs";
import * as path from "path";

export function runSlither(filePath: string): string {
  const absolutePath = path.resolve(filePath);
  const outputFile = path.join(process.cwd(), "slither-report.json");

  console.log("\x1b[36m%s\x1b[0m", `Analyse of contract : ${absolutePath}`);
  const result = spawnSync("slither", [absolutePath, "--json", outputFile], { stdio: "inherit" });

  if (result.error) {
    console.error("\x1b[31m%s\x1b[0m", "Impossible to execute slither :", result.error);
    throw result.error;
  }

  if (result.status !== 0 && result.status !== 255) {
    console.error("\x1b[33m%s\x1b[0m",`Slither terminated with status : ${result.status}`);
  }

  if (!fs.existsSync(outputFile)) {
    throw new Error("None file generated by slither");
  }

  console.log("\x1b[32m%s\x1b[0m", `Report generated : ${outputFile}`);
  return outputFile;
}

export function readSlitherReport(filePath: string): any {
  const data = fs.readFileSync(filePath, "utf8");
  return JSON.parse(data);
}
